import 'package:cloud_firestore/cloud_firestore.dart' as firestore;
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_osm_plugin/flutter_osm_plugin.dart' as osm;

import '../../modules/home_page/model/geofence_model.dart';
import 'geofence_converter.dart';

class GeoFenceService {
  final firestore.FirebaseFirestore _firestore = firestore.FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  firestore.CollectionReference get _geofencesCollection => _firestore.collection('geofences');

  /// Create or update geofence (only one active geofence at a time)
  Future<GeoFenceModel> createOrUpdateGeoFence(osm.GeoPoint osmCenter, double radius) async {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      throw Exception('No user logged in');
    }

    try {
      // Convert OSM GeoPoint to Firestore GeoPoint
      final firestore.GeoPoint firestoreCenter = GeoPointConverter.toFirestoreGeoPoint(osmCenter);

      // First, check if there's an existing geofence
      final firestore.QuerySnapshot existingGeofences = await _geofencesCollection.get();

      GeoFenceModel geofence;

      if (existingGeofences.docs.isNotEmpty) {
        // Update existing geofence (only one should exist)
        final firestore.DocumentSnapshot existingDoc = existingGeofences.docs.first;
        geofence = GeoFenceModel.fromFirestore(existingDoc).copyWith(
          center: firestoreCenter,
          radius: radius,
          updatedAt: DateTime.now(),
        );

        await _geofencesCollection.doc(existingDoc.id).update(geofence.toJson());
      } else {
        // Create new geofence
        geofence = GeoFenceModel(
          id: '', // ID will be generated by Firestore
          center: firestoreCenter,
          radius: radius,
          createdBy: currentUser.uid,
          createdAt: DateTime.now(),
        );

        final firestore.DocumentReference docRef = await _geofencesCollection.add(geofence.toJson());
        // Update the geofence with the generated ID
        geofence = geofence.copyWith(id: docRef.id);
      }

      return geofence;
    } catch (e) {
      print('Error creating/updating geofence: $e');
      rethrow;
    }
  }

  /// Insert a new geofence point (creates new document)
  Future<GeoFenceModel> insertGeoPoint(osm.GeoPoint osmCenter, double radius) async {
    final User? currentUser = _auth.currentUser;
    if (currentUser == null) {
      throw Exception('No user logged in');
    }

    try {
      // Convert OSM GeoPoint to Firestore GeoPoint
      final firestore.GeoPoint firestoreCenter = GeoPointConverter.toFirestoreGeoPoint(osmCenter);

      // Create new geofence
      final geofence = GeoFenceModel(
        id: '', // ID will be generated by Firestore
        center: firestoreCenter,
        radius: radius,
        createdBy: currentUser.uid,
        createdAt: DateTime.now(),
      );

      // Add to Firestore and get the generated ID
      final firestore.DocumentReference docRef = await _geofencesCollection.add(geofence.toJson());

      // Return the geofence with the actual Firestore ID
      return geofence.copyWith(id: docRef.id);
    } catch (e) {
      print('Error inserting geo point: $e');
      rethrow;
    }
  }

  /// Get the current active geofence
  Future<GeoFenceModel?> getActiveGeoFence() async {
    try {
      final firestore.QuerySnapshot geofences = await _geofencesCollection
          .orderBy('createdAt', descending: true)
          .limit(1)
          .get();

      if (geofences.docs.isNotEmpty) {
        return GeoFenceModel.fromFirestore(geofences.docs.first);
      }
      return null;
    } catch (e) {
      print('Error getting active geofence: $e');
      rethrow;
    }
  }

  /// Get geofence by ID
  Future<GeoFenceModel?> getGeoFenceById(String geofenceId) async {
    try {
      final firestore.DocumentSnapshot doc = await _geofencesCollection.doc(geofenceId).get();
      if (doc.exists) {
        return GeoFenceModel.fromFirestore(doc);
      }
      return null;
    } catch (e) {
      print('Error getting geofence by ID: $e');
      rethrow;
    }
  }

  /// Delete the current geofence
  Future<void> deleteGeoFence() async {
    try {
      final firestore.QuerySnapshot geofences = await _geofencesCollection.get();

      if (geofences.docs.isNotEmpty) {
        await _geofencesCollection.doc(geofences.docs.first.id).delete();
      }
    } catch (e) {
      print('Error deleting geofence: $e');
      rethrow;
    }
  }

  /// Delete geofence by ID
  Future<void> deleteGeoFenceById(String geofenceId) async {
    try {
      await _geofencesCollection.doc(geofenceId).delete();
    } catch (e) {
      print('Error deleting geofence by ID: $e');
      rethrow;
    }
  }

  /// Get all geofences (for admin purposes)
  Future<List<GeoFenceModel>> getAllGeofences() async {
    try {
      final firestore.QuerySnapshot geofences = await _geofencesCollection
          .orderBy('createdAt', descending: true)
          .get();

      return geofences.docs.map((doc) {
        return GeoFenceModel.fromFirestore(doc);
      }).toList();
    } catch (e) {
      print('Error getting all geofences: $e');
      rethrow;
    }
  }

  /// Stream for real-time geofence updates
  Stream<GeoFenceModel?> streamActiveGeoFence() {
    return _geofencesCollection
        .orderBy('createdAt', descending: true)
        .limit(1)
        .snapshots()
        .map((snapshot) {
      if (snapshot.docs.isNotEmpty) {
        return GeoFenceModel.fromFirestore(snapshot.docs.first);
      }
      return null;
    });
  }

  /// Check if any geofence exists
  Future<bool> hasActiveGeoFence() async {
    try {
      final firestore.QuerySnapshot geofences = await _geofencesCollection
          .limit(1)
          .get();

      return geofences.docs.isNotEmpty;
    } catch (e) {
      print('Error checking if geofence exists: $e');
      rethrow;
    }
  }

  /// Update geofence radius
  Future<GeoFenceModel> updateGeoFenceRadius(String geofenceId, double newRadius) async {
    try {
      final geofence = await getGeoFenceById(geofenceId);
      if (geofence == null) {
        throw Exception('Geofence not found');
      }

      final updatedGeofence = geofence.copyWith(
        radius: newRadius,
        updatedAt: DateTime.now(),
      );

      await _geofencesCollection.doc(geofenceId).update(updatedGeofence.toJson());
      return updatedGeofence;
    } catch (e) {
      print('Error updating geofence radius: $e');
      rethrow;
    }
  }

  /// Update geofence center
  Future<GeoFenceModel> updateGeoFenceCenter(String geofenceId, osm.GeoPoint osmCenter) async {
    try {
      final geofence = await getGeoFenceById(geofenceId);
      if (geofence == null) {
        throw Exception('Geofence not found');
      }

      // Convert OSM GeoPoint to Firestore GeoPoint
      final firestore.GeoPoint firestoreCenter = GeoPointConverter.toFirestoreGeoPoint(osmCenter);

      final updatedGeofence = geofence.copyWith(
        center: firestoreCenter,
        updatedAt: DateTime.now(),
      );

      await _geofencesCollection.doc(geofenceId).update(updatedGeofence.toJson());
      return updatedGeofence;
    } catch (e) {
      print('Error updating geofence center: $e');
      rethrow;
    }
  }

  /// Clear all geofences (for testing/development)
  Future<void> clearAllGeofences() async {
    try {
      final firestore.QuerySnapshot geofences = await _geofencesCollection.get();

      for (final doc in geofences.docs) {
        await _geofencesCollection.doc(doc.id).delete();
      }
    } catch (e) {
      print('Error clearing all geofences: $e');
      rethrow;
    }
  }
}